### ISSUE TITLE
Web page test results 

### ISSUE THREAD

**Issue by sagehartly** [sagehartly/dsn1675-project-1b#6]
@thomasjbradley

Just realized I submitted my assignment without doing a final web page speed test and now I can't get it to be under 1sec. I changed all my icons to svg files and then ran them through the svgo-gui test but I still can't get my web page test results to be under one second. It's at 1.098 - is that close enough? My two images are 71kb and 85kb. The icons are 2kb, 2kb and 638b. 

I only have 2 fonts as well and took out the unused font weight in the html in case that made a difference.

Other than fonts and images, I'm not sure what else to do - thanks!

<img width="965" alt="screen shot 2015-10-10 at 3 39 46 pm" src="https://cloud.githubusercontent.com/assets/10467637/10412938/2c4713c2-6f65-11e5-8daf-6633a64cdaf5.png">

Thanks!
- Sage

**Comment by thomasjbradley** [comment]
1.098 is perfect!

**Comment by sagehartly** [comment]
Woo hoo! Thanks! Thought it had to be under a second!
